In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,f1_score

In [ ]:
df=pd.read_csv("creditcard.csv")

In [ ]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,152055,2.137513,-1.774889,0.123651,-1.496837,-2.170251,-0.300998,-1.892327,0.150420,-0.779665,...,-0.069577,0.198567,0.342330,0.020888,-0.645078,-0.280447,0.049397,-0.036202,39.32,0.0
1,152055,2.086303,0.222409,-1.748963,0.371876,0.576037,-0.769118,0.246946,-0.280569,0.360922,...,-0.363851,-0.895797,0.308897,0.404924,-0.205204,0.178142,-0.056736,-0.029960,1.98,0.0
2,152056,1.704365,-0.167720,-2.592158,1.220890,1.042788,-0.771913,1.220637,-0.460107,-0.651317,...,0.472828,1.107012,-0.357666,0.776130,0.798962,-0.266483,-0.090974,-0.049278,186.24,0.0
3,152057,1.911497,0.663399,-0.886052,3.490222,0.846244,0.318316,0.227846,-0.021496,-1.549709,...,0.291272,0.833430,0.086110,0.718088,0.128834,0.079201,-0.045118,-0.053783,2.28,0.0
4,152057,1.816562,-0.772929,-0.886973,-0.198932,0.351746,1.801854,-0.956822,0.605862,0.886718,...,0.280947,0.874777,0.180991,-0.899702,-0.511685,0.729750,-0.005731,-0.062497,50.00,0.0

In [ ]:
df.shape

(2892, 31)

In [ ]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,2892.000000,2892.000000,2892.000000,2892.000000,2892.000000,2892.000000,2892.000000,2891.000000,2891.000000,2891.000000,...,2891.000000,2891.000000,2891.000000,2891.000000,2891.000000,2891.000000,2891.000000,2891.000000,2891.000000,2891.000000
mean,152653.898340,0.321079,-0.058553,-0.808375,-0.204944,0.255550,-0.111498,0.068082,-0.012553,-0.050070,...,0.070744,0.109176,0.029992,0.013907,-0.151226,0.011748,-0.016058,-0.011185,84.516257,0.002075
std,346.171461,2.051635,1.703283,1.418831,1.437325,1.389437,1.417793,1.232823,0.995880,0.962139,...,0.685229,0.788583,0.585765,0.608140,0.546876,0.465761,0.414961,0.386648,253.800911,0.045517
min,152055.000000,-22.859099,-29.336007,-12.714462,-4.039829,-11.203509,-17.282140,-21.116854,-15.190517,-3.408239,...,-4.801821,-5.404703,-9.173325,-1.821121,-2.935228,-1.500278,-9.845808,-3.675632,0.000000,0.000000
25%,152366.500000,-0.740729,-0.699959,-1.660777,-0.975068,-0.441218,-0.927529,-0.485580,-0.283592,-0.612878,...,-0.220024,-0.546231,-0.133243,-0.353273,-0.443855,-0.276205,-0.076281,-0.063285,6.050000,0.000000
50%,152638.500000,0.180170,-0.028191,-0.782933,-0.354142,0.213241,-0.413711,0.129177,-0.038821,-0.001333,...,0.035801,0.180410,0.045296,0.029973,-0.216278,0.000464,-0.013118,-0.029550,19.990000,0.000000
75%,152962.000000,2.000051,0.778699,0.040897,0.416729,0.852656,0.230192,0.687116,0.300660,0.533975,...,0.262601,0.744791,0.235252,0.538877,0.210741,0.251354,0.083405,0.064898,71.900000,0.000000
max,153254.000000,2.408683,9.045855,3.633601,10.278237,28.516513,10.821301,17.911884,7.167686,5.984234,...,10.152476,2.215143,7.810062,3.580256,1.962164,2.903063,3.992898,15.407019,8787.000000,1.000000

In [ ]:
df["Class"]==1

0       False
1       False
2       False
3       False
4       False
        ...
2887    False
2888    False
2889    False
2890    False
2891    False
Name: Class, Length: 2892, dtype: bool

In [ ]:
df["Class"].value_counts()

0.0    2885
1.0       6
Name: Class, dtype: int64

In [ ]:
df.dtypes

Time        int64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class     float64
dtype: object